// Define the structure for the Supabase product_inventory table
// This should match the Product interface in productInventory.ts
export interface ProductInventory {
  // id column has been removed, product_id is now the primary key
  product_id: string;
  name: string;
  url: string;
  price: string;
  rating: number | null;
  rating_count: number | null;
  social_proof_1: string | null;
  social_proof_2: string | null;
  social_proof_3: string | null;
  social_proof_4: string | null;
  subcategory: string;
  description: string;
  extra_description: string | null;
  comments: any[] | null; // Parsed JSON array
  rating_score: number | null;
  total_comment_count: number | null;
  average_rating: number | null;
  total_rating_count: number | null;
  total_pages: number | null;
  star_0_count: number | null;
  star_1_count: number | null;
  star_2_count: number | null;
  star_3_count: number | null;
  star_4_count: number | null;
  star_5_count: number | null;
  total_questions: number | null;
  total_qa_pages: number | null;
  questions: any[] | null; // Parsed JSON array
  question_tags: null; // Changed from string[] | null to match Product interface
  Menşei: string | null;
  RGB: string | null;
  Renk: string | null;
  stock_quantity: number; // Added for inventory management
  created_at?: string; // Auto-generated by Supabase
  updated_at?: string; // Auto-generated by Supabase
} 